### PR TITLE
fixing global exports bug

### PR DESCRIPTION
**Pull request by davidchase**
using rollup let me know if this works for you guys

### CODE REVIEW

**Comment by briancavalier** [comment]
Hmm, isparta (as it tends to do) seems to be eating the detail of why travis is failing.  Any idea what's going on?

**Comment by davidchase** [comment]
hmm i will explore why its failing maybe istanbul + mocha will be better ?

**Comment by briancavalier** [comment]
Are the tests passing for you locally?

**Comment by davidchase** [comment]
nope same error 😞

**Comment by briancavalier** [comment]
Hmmm, ok.  One thing you can try is to run mocha without isparta to see if that surfaces the real error, i.e. `./node_modules/.bin/mocha`

**Comment by davidchase** [comment]
will do 👍

**Comment by davidchase** [comment]
``` sh
mostjs/create/test/index-test.js:1
(function (exports, require, module, __filename, __dirname) { import { describe, it } from 'mocha'
                                                              ^^^^^^

SyntaxError: Unexpected reserved word
```

looks its not liking the `import` if only there was something like buble + buba ;)

**Comment by briancavalier** [comment]
Nice work, @davidchase!  Thank you.

**Comment by nissoh** [comment]
@davidchase, i can't import this module using typescript. checked with TS v1.8.10
v1.0.1 is working fine.

**Pull request merged**
